- project:
    templates:
      - check-requirements
      - build-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
