- job:
    name: apmec-functional-devstack
    parent: devstack
    description: |
      Base job for devstack-based functional tests
    pre-run: playbooks/devstack/pre.yaml
    run: playbooks/devstack/run.yaml
    post-run: playbooks/devstack/post.yaml
    roles:
      - zuul: openstack-infra/devstack
    timeout: 9000
    required-projects:
      - openstack/aodh
      - openstack/horizon
      - openstack/barbican
      - openstack/ceilometer
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/networking-sfc
      - openstack/python-barbicanclient
      - openstack/python-mistralclient
      - openstack/python-tackerclient
      - openstack/tacker
      - openstack/tacker-horizon
    vars:
      test_matrix_configs: [neutron]
      devstack_services:
        horizon: true
        tacker: true
        tacker-conductor: true
        swift: false
      devstack_plugins:
        heat: https://git.openstack.org/openstack/heat
        networking-sfc: https://git.openstack.org/openstack/networking-sfc
        aodh: https://git.openstack.org/openstack/aodh
        ceilometer: https://git.openstack.org/openstack/ceilometer
        barbican: https://git.openstack.org/openstack/barbican
        mistral: https://git.openstack.org/openstack/mistral
        tacker: https://git.openstack.org/openstack/tacker
      tox_install_siblings: false
      tox_envlist: dsvm-functional
      zuul_work_dir: src/git.openstack.org/openstack/tacker

- job:
    name: tacker-functional-devstack-python3
    parent: tacker-functional-devstack
    description: |
      Run tacker functional tests using python3 against a master devstack
    vars:
      tacker_environment:
        TACKER_TOX_PYTHON: python3

- project:
    check:
      jobs:
        - tacker-functional-devstack:
            voting: false
        - tacker-functional-devstack-python3:
            voting: false
        - openstack-tox-lower-constraints
